pyms:
  requests:
    data: ""
  swagger:
    path: "swagger"
    file: "swagger.yaml"
  tracer:
    client: "jaeger"
    host: "localhost"
    component_name: "Chat BaaS"
  config:
    DEBUG: true
    TESTING: true
    APP_NAME: project
    APPLICATION_ROOT : /
    SECRET_KEY: "gjr39dkjn344_!67#"
    service_host: http://localhost:8081/